In [1]:
# analysis on last 100
# check for predicted vs outcome eucl dist
from utils import * 
from RED import * 
from scipy.stats import norm

# data
last_100_path = os.path.join(utils.mypath, 'Result', 'last_100.json')
last_100 = utils.open_json(last_100_path)

monte_carlo_result_path = os.path.join(utils.mypath, 'Result', 'monte_carlo_result.json')
monte_carlo_result = utils.open_json(monte_carlo_result_path)

weatherHistory_path = os.path.join(utils.mypath, 'Storage', 'weatherHistory_cleaned.csv')
weatherHistory = pd.read_csv(weatherHistory_path, index_col = [0])

# calculate error from RED algorithm
result = {}
for k,v in last_100.items():
    outcome_idx = eval(k)[-1]
    predict_idx = eval(list(v.items())[0][0])[-1]
    
    if outcome_idx > weatherHistory.index[-1]:
        continue

    outcome = weatherHistory.loc[[outcome_idx]].values
    prediction = weatherHistory.loc[[predict_idx]].values
    error = eucl_dist(outcome, prediction) # prediction error
    
    result[k] = error
    
result = dict(sorted(result.items(), key=lambda item: item[1]))

# compare to randomized result for statistical significance testing
RED_mean_error = np.mean(list(result.values()))

RAND_mean_error = np.mean(monte_carlo_result)
RAND_std_error = np.std(monte_carlo_result)

pvalue = norm(RAND_mean_error, RAND_std_error).pdf(RED_mean_error)
print(pvalue)

0.0005368252940805353

In [4]:
df_path = os.path.join(utils.mypath, 'Storage', 'weatherHistory.csv')
df = pd.read_csv(df_path)

In [5]:
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [18]:
# predictors
df[96428:96430]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96428,2016-09-08 23:00:00.000 +0200,Partly Cloudy,rain,18.350000,18.350000,0.77,3.2200,53.0,15.5526,0.0,1014.68,Partly cloudy starting overnight.
96429,2016-09-09 00:00:00.000 +0200,Partly Cloudy,rain,17.755556,17.755556,0.81,2.9624,12.0,16.1000,0.0,1014.65,Partly cloudy starting in the morning.

In [19]:
df.iloc[[96430]]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96430,2016-09-09 01:00:00.000 +0200,Clear,rain,16.622222,16.622222,0.87,3.4293,349.0,16.1,0.0,1014.56,Partly cloudy starting in the morning.

In [20]:
# predictions
df[96402:96404]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96402,2016-09-07 21:00:00.000 +0200,Partly Cloudy,rain,19.838889,19.838889,0.79,3.22,40.0,16.1,0.0,1019.83,Partly cloudy throughout the day.
96403,2016-09-07 22:00:00.000 +0200,Partly Cloudy,rain,18.727778,18.727778,0.84,0.00,0.0,16.1,0.0,1019.64,Partly cloudy throughout the day.

In [21]:
df.iloc[[96404]]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96404,2016-09-07 23:00:00.000 +0200,Partly Cloudy,rain,17.661111,17.661111,0.88,3.22,10.0,15.1501,0.0,1019.39,Partly cloudy throughout the day.

In [15]:
last_100['(96428, 96430)']

{'(96402, 96404)': 0.09282757180579558,
 '(71447, 71449)': 0.10096692754884731,
 '(45195, 45197)': 0.10647733947404225,
 '(65255, 65257)': 0.10965471403699273,
 '(83061, 83063)': 0.11101569984869569,
 '(88625, 88627)': 0.11409164092517503,
 '(4270, 4272)': 0.11497196825362135,
 '(95783, 95785)': 0.11916649475899255,
 '(22370, 22372)': 0.1194352672146956,
 '(31391, 31393)': 0.12155330046167931}

In [6]:
result

{'(96443, 96445)': 0.02521518225556917,
 '(96444, 96446)': 0.05669309276036534,
 '(96373, 96375)': 0.061174177797635454,
 '(96445, 96447)': 0.07258995338828694,
 '(96368, 96370)': 0.08110523085211371,
 '(96379, 96381)': 0.08843718654228638,
 '(96366, 96368)': 0.09079021054735102,
 '(96421, 96423)': 0.0948344764605447,
 '(96355, 96357)': 0.09536187585666422,
 '(96374, 96376)': 0.09717013536150128,
 '(96441, 96443)': 0.09771178601436392,
 '(96449, 96451)': 0.1017580789201097,
 '(96402, 96404)': 0.10231968659200165,
 '(96380, 96382)': 0.10278862491062932,
 '(96412, 96414)': 0.1032923990114186,
 '(96446, 96448)': 0.10971645661162531,
 '(96429, 96431)': 0.1111241179936275,
 '(96415, 96417)': 0.11325807595666025,
 '(96440, 96442)': 0.11601139685535174,
 '(96371, 96373)': 0.11798078700531629,
 '(96359, 96361)': 0.11974888031085483,
 '(96372, 96374)': 0.12247406389324164,
 '(96434, 96436)': 0.1244728552354321,
 '(96363, 96365)': 0.12461753456834088,
 '(96442, 96444)': 0.12665664065457513,
 '(96388, 96390)': 0.12751199074420522,
 '(96430, 96432)': 0.12898598796429311,
 '(96439, 96441)': 0.1340677452330664,
 '(96354, 96356)': 0.13592824345071092,
 '(96401, 96403)': 0.1426700487891899,
 '(96385, 96387)': 0.14725006434125368,
 '(96396, 96398)': 0.14995552587062616,
 '(96397, 96399)': 0.15173210000628817,
 '(96425, 96427)': 0.1572510908867245,
 '(96369, 96371)': 0.1573734997353306,
 '(96367, 96369)': 0.16207377410100968,
 '(96410, 96412)': 0.16629988893176872,
 '(96420, 96422)': 0.16751582287826672,
 '(96392, 96394)': 0.16794372313167763,
 '(96365, 96367)': 0.16869873061824547,
 '(96356, 96358)': 0.16874701849659285,
 '(96391, 96393)': 0.17122753621247058,
 '(96438, 96440)': 0.17361425560045093,
 '(96376, 96378)': 0.17718478959371273,
 '(96436, 96438)': 0.17885923909463214,
 '(96387, 96389)': 0.18039693196495532,
 '(96360, 96362)': 0.18044457130621702,
 '(96408, 96410)': 0.18272887226643947,
 '(96417, 96419)': 0.18399840693742386,
 '(96418, 96420)': 0.18500574078201423,
 '(96395, 96397)': 0.1922933001254707,
 '(96416, 96418)': 0.20230358741002819,
 '(96370, 96372)': 0.20625798809840626,
 '(96406, 96408)': 0.20684336903117134,
 '(96361, 96363)': 0.21489141296182576,
 '(96358, 96360)': 0.2176354673137858,
 '(96422, 96424)': 0.21971826426607044,
 '(96450, 96452)': 0.23266580167172227,
 '(96386, 96388)': 0.23584609361736394,
 '(96390, 96392)': 0.24041897145413724,
 '(96437, 96439)': 0.24379775443770352,
 '(96403, 96405)': 0.24917803950719358,
 '(96447, 96449)': 0.2541302571089054,
 '(96409, 96411)': 0.2719844502254723,
 '(96384, 96386)': 0.28065100576760826,
 '(96382, 96384)': 0.3020717441059368,
 '(96423, 96425)': 0.3341044107531023,
 '(96432, 96434)': 0.33672208566156187,
 '(96414, 96416)': 0.33779768129681953,
 '(96389, 96391)': 0.3502373960225609,
 '(96394, 96396)': 0.35619926267524743,
 '(96405, 96407)': 0.3724527087948408,
 '(96448, 96450)': 0.383687122479519,
 '(96375, 96377)': 0.39895189885562066,
 '(96399, 96401)': 0.4143912827225817,
 '(96353, 96355)': 0.4363667161632162,
 '(96393, 96395)': 0.47731583410895556,
 '(96381, 96383)': 0.4922716207133094,
 '(96424, 96426)': 0.5058269312538551,
 '(96413, 96415)': 0.6166410180330206,
 '(96419, 96421)': 0.6211277818784888,
 '(96377, 96379)': 0.6662514262709566,
 '(96357, 96359)': 0.7765956926640184,
 '(96398, 96400)': 0.7936968477029076,
 '(96426, 96428)': 0.8021485558138728,
 '(96407, 96409)': 0.8309096324454676,
 '(96433, 96435)': 0.836256641245543,
 '(96404, 96406)': 0.8540922679134195,
 '(96364, 96366)': 0.8557953049538836,
 '(96400, 96402)': 0.8574091345366077,
 '(96427, 96429)': 0.8725234705560435,
 '(96411, 96413)': 0.8782516340933377,
 '(96431, 96433)': 0.8931031152215657,
 '(96362, 96364)': 0.9074462266374299,
 '(96378, 96380)': 0.9400171742077116,
 '(96435, 96437)': 0.943247885958871,
 '(96383, 96385)': 0.9632916160331435,
 '(96428, 96430)': 0.9658165309845982}